backend:
  name: github
  repo: ngvnguyen09/nctitc
  branch: main
  # Đây là bí kíp: Dùng một cổng Auth trung gian miễn phí
  base_url: https://decap-cms-oauth.vercel.app
  auth_endpoint: /api/auth

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Bài Viết"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Tiêu đề", name: "title", widget: "string"}
      - {label: "Ngày đăng", name: "date", widget: "datetime"}
      - {label: "Mô tả", name: "description", widget: "string"}
      - {label: "Nội dung", name: "body", widget: "markdown"}
